# docker-compose build --no-cache && docker-compose up
services:
  frontend:
    build: ./frontend                
    ports:
      - "5173:5173"                            
    environment:
      - VITE_API_URL=${VITE_API_URL}  
    depends_on:
      - backend                      

  backend:
    build: ./backend                  
    ports:
      - "8000:8000"                   
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - db                            
    volumes:
      - ./backend:/app                

  db:
    image: postgres:15                
    environment:
      POSTGRES_USER: ${POSTGRES_USER}         
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}     
      POSTGRES_DB: ${POSTGRES_DB}            
    volumes:
      - pgdata:/var/lib/postgresql/data  
    ports:
      - "5433:5432"                   
    restart: always

volumes:
  pgdata: