# docker-compose build --no-cache && docker-compose up
services:
  frontend:
    build: ./frontend                
    ports:
      - "5173:5173"  
    env_file: .env                          
    environment:
      - VITE_API_URL=${VITE_API_URL}  
    depends_on:
      - backend    
    volumes:
    - ./frontend:/app
    - /app/node_modules                  

  backend:
    build: ./backend                  
    ports:
      - "8000:8000"   
    env_file: .env                
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - SECRET_KEY=${SECRET_KEY}
      - SYMMETRIC_ALGORITHM=${SYMMETRIC_ALGORITHM}
    depends_on:
      - db                            
    volumes:
      - ./backend:/app                

  db:
    image: postgres:15  
    env_file: .env              
    environment:
      POSTGRES_USER: ${POSTGRES_USER}         
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}     
      POSTGRES_DB: ${POSTGRES_DB}            
    volumes:
      - pgdata:/var/lib/postgresql/data  
    ports:
      - "5433:5432"                   
    restart: always

volumes:
  pgdata: