"""
Database model for the ToDo entity.

This model defines the structure of the 'todos' table in the database.
It uses SQLModel to enable ORM functionality and type annotations.

Attributes:
    id (int): Primary key, auto-generated.
    title (str): The title or description of the task.
    due_to (datetime | None): Optional due date of the task.
    is_done (bool): Whether the task has been completed.
    user_id (int): Foreign key referencing the 'users' table.
"""

from sqlmodel import SQLModel, Field, ForeignKey
from datetime import datetime

class ToDo(SQLModel, table=True):
  __tablename__ = "todos"
  id: int | None = Field(default=None, primary_key=True, nullable=False) # will be auto-generated by the database
  title: str
  due_to: datetime | None = Field(default=None)
  is_done: bool
  user_id: int = Field(ForeignKey("users.id"), nullable=False)