"""
Database model for the User entity.

This model defines the structure of the 'users' table in the database.
It includes authentication-relevant fields and is used for DB operations.

Attributes:
    id (int): Primary key, auto-generated.
    username (str): Unique username of the user.
    hashed_password (str): Hashed password for authentication.
"""

from sqlmodel import SQLModel, Field

class User(SQLModel, table=True):
  __tablename__ = "users"
  id: int | None = Field(default=None, primary_key=True, nullable=False) # will be auto-generated by the database
  username: str = Field(unique=True)
  hashed_password: str